### ISSUE TITLE
Transport not connected error if you wait 1 min between inventory runs

### ISSUE THREAD

**Issue by SteGriff** [NordicID/nur_sample_windows#3]
I am using an EXA51 and the NurApiSampleMvvm app.

To reproduce the bug:

 * Connect to a reader
 * Start inventory streaming
 * Scan a few items
 * Stop inventory streaming
 * Wait at least 60 seconds
 * Start a new inventory streaming

When I do this, the reader disconnects, plays its 'error' sound, and I get an error message on the screen:

![transport-error](https://user-images.githubusercontent.com/3997617/34519076-563c60f4-f07a-11e7-91e9-6532b5dccfef.PNG)

I have written my own app which is similar to the sample and it also exhibits this problem, and I was able to capture all of the LogEvents from the reader.

```
Api_LogEvent message:<E>NurApiXchPacketLock() cmd 0x22; error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<E>SetModuleSetupLock() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<E>NurBootSetup() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<E>NurApiXchPacketLock() Transport not connected: 4098
Api_LogEvent message:<E>NurApiGetVersions() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<E>NurApiGetMode() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<E>NurApiGetDeviceCaps() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<E>NurApiGetReaderInfo() error: 4098 (0x1002) (Transport not connected)
Disconnected!!
```

Please note that after the 60 seconds timeout, I am still able to use *other* features of the reader including the barcode scanner. It is just inventory and streaming inventory which cause it to disconnect and throw the error.

Do we need to manually re-connect to the reader before doing an inventory stream if the device has reached some "timeout" period?

Thanks and regards
Ste

**Comment by mikkonid** [comment]
I tried to reproduce issue here, but it seems to work fine.

Can you try to capture logs, with more verbose API logs:
`api.SetLogLevel(NurApi.LOG_ERROR | NurApi.LOG_USER | NurApi.LOG_VERBOSE | NurApi.LOG_DATA);`

What FW version your EXA51 is running?
You can check it in MVVM sample accessory page.

What FW version your EXA51 RFID (NUR) module is running?
You can check it in MVVM sample bottom status bar, when device is connected.

BR,
Mikko

**Comment by SteGriff** [comment]
Hi Mikko,

Status bar in sample app says:
```
Connected NUR-10W | Serial K164702307 | FW 5.7 A
```

I can't open the accessory page - I get this error:

![accessory-page](https://user-images.githubusercontent.com/3997617/34527780-8eab9742-f09e-11e7-8919-e4d068657244.PNG)

(It's always done that for me)

By the way, here is the workflow for my app:

 * User presses trigger
 * Device scans for a QR code
 * When the device has seen a QR code, it goes into streaming inventory mode 
 * (User presses trigger again to stop streaming)

Here is the verbose log from the failing operation:

```
Api_LogEvent message:<D>RD 12: A5060001005D8100640183F8
Api_LogEvent message:<V>I/O change, source=100, direction = 1, sensor: NO
Api_LogEvent message:<D>RD 12: A5060001005D81006400A2E8
Api_LogEvent message:<V>I/O change, source=100, direction = 0, sensor: NO
Scanning for barcodes...
Api_LogEvent message:<V>NurApiCustomCmd(0000000000000055, 1415050304, 3, 0000000000000000, 0, 0000000000000000)
Api_LogEvent message:<V>NurApiXchPacketLock() Send command 0x55; timeout 5000; lock 1; cmdParamsLen 3
Api_LogEvent message:<D>WR 12: A5060000005C5506B80BD1D9
Api_LogEvent message:<D>RD 10: A5040000005E550045EC
Api_LogEvent message:<V>PacketXchReadThread() Got response packet for cmd 0x55 (2 bytes)
Api_LogEvent message:<D>RD 18: A50C000100579000017461626C65330D1833
Barcode(0): table3
Api_LogEvent message:<V>NurApiCustomCmd(0000000000000055, 1405087712, 3, 0000000000000000, 0, 0000000000000000)
Api_LogEvent message:<V>NurApiXchPacketLock() Send command 0x55; timeout 5000; lock 1; cmdParamsLen 3
Api_LogEvent message:<D>WR 12: A5060000005C55086400F123
Api_LogEvent message:<D>RD 10: A5040000005E550045EC
Api_LogEvent message:<V>PacketXchReadThread() Got response packet for cmd 0x55 (2 bytes)
Api_LogEvent message:<V>NurApiXchPacketLock() Send command 0x5; timeout 5000; lock 1; cmdParamsLen 0
Api_LogEvent message:<V>NurApiCustomCmd(0000000000000055, 1449389168, 3, 0000000000000000, 0, 0000000000000000)
Api_LogEvent message:<D>WR 9: A503000000590555B1
Api_LogEvent message:<D>RD 14: A508000110438000415050006992
Api_LogEvent message:<D>RD 10: A5040000005E0500FAE2
Api_LogEvent message:<V>PacketXchReadThread() Got response packet for cmd 0x5 (2 bytes)
Api_LogEvent message:<V>NurApiXchPacketLock() Send command 0x55; timeout 5000; lock 1; cmdParamsLen 3
Api_LogEvent message:<V>NurApiHandleInventoryStream(5457f1c8, 1)
Api_LogEvent message:<D>WR 12: A5060000005C55086400F123
Api_LogEvent message:<D>RD 10: A5040000005E550045EC
Api_LogEvent message:<V>PacketXchReadThread() Got response packet for cmd 0x55 (2 bytes)
Api_LogEvent message:<V>NurApiXchPacketLock() Send command 0x39; timeout 5000; lock 1; cmdParamsLen 1
Api_LogEvent message:<D>WR 10: A5040000005E390002A2
Api_LogEvent message:<D>RD 10: A5040000005E390002A2
Api_LogEvent message:<V>PacketXchReadThread() Got response packet for cmd 0x39 (2 bytes)
Api_LogEvent message:<V>NurBootSetup(1) connected 1
Api_LogEvent message:<V>SetModuleSetupLock() flags 1fffffff lock 0
Api_LogEvent message:<V>NurApiXchPacketLock() Send command 0x22; timeout 5000; lock 0; cmdParamsLen 91
Api_LogEvent message:<D>RD 20: A5220001106982000005F3000718CE413300AC3C
Api_LogEvent message:<D>RD 20: 0D000030030035E017004FAA33F600000606FB1B
Api_LogEvent message:<V>ParseIdBuffer() Added 1 tags; storage count 1, IR data = NO.
Api_LogEvent message:<E>NurApiXchPacketLock() cmd 0x22; error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<E>SetModuleSetupLock() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<E>NurBootSetup() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<V>*** InternalGetAllInformationUnlocked : call from BOOT SETUP ***
Api_LogEvent message:<V>InternalGetAllInformationUnlocked()
Api_LogEvent message:<V>PacketXchReadThread() EXIT; connected 1
Api_LogEvent message:<V>NurApiDisconnectedInternal() 0
Api_LogEvent message:<E>NurApiXchPacketLock() Transport not connected: 4098
Api_LogEvent message:<E>NurApiGetVersions() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<V>InternalGetAllInformationUnlocked() isL2Module 0
Api_LogEvent message:<V>StreamTimeoutThread()-
Api_LogEvent message:<E>NurApiGetMode() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<V>InternalGetAllInformationUnlocked() mode 'X'
Api_LogEvent message:<E>NurApiGetDeviceCaps() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<V>InternalGetAllInformationUnlocked() devCaps result = 4098
Api_LogEvent message:<E>NurApiGetReaderInfo() error: 4098 (0x1002) (Transport not connected)
Api_LogEvent message:<V>InternalGetAllInformationUnlocked() readerinfo = 4098; version 5.7-A (0)
Api_LogEvent message:<V>PacketXchReadThread() Exit
Disconnected!!
```

Looking at this log, I wonder whether I could copy what the Android app does when it says

```
// Restart reading if needed
if (event.stopped && mInventoryRunning) {

try {
	mApi.startInventoryStream();
	...
```

Thanks as always for your support
Ste

**Comment by mikkonid** [comment]
Hi Ste,

Looking at logs, it seems that BT link just gets disconnected for some reason. Does it cut connection immediately, or does it freeze for a while before connection is cut?

Can you update device and NUR FW with android app?
Updates are available in [Android RFID Demo](https://play.google.com/store/apps/details?id=com.nordicid.rfiddemo) "Settings" -> "Firmware update" page.

Latest EXA fw is 2.2.0-H / L; Where H=high speed (BLE 4.2 or newer) and L=low speed (BLE 4.1 or older)
And latest NUR1 FW is 5.10-A


MVVM sample does same:
```
            // Restart stream if needed
            if (mStreamRunning && e.data.stopped)
            {
                App.NurApi.StartInventoryStream();
            }
```
Checking for mStreamRunning is needed,because NUR will send stream stopped event when it is auto stopped by 20sec timer or when StopInventoryStream() is called. 

In case of StopInventoryStream() we set mStreamRunning to false, thus we don't start stream again.


BR,
Mikko

**Comment by SteGriff** [comment]
Hi Mikko,

It cuts out pretty quickly; it plays the error sound about 1-2 sec after the barcode read has finished.

I was able to update the NUR firmware to `5.10-A` but I cannot update the Device firmware or Device bootloader, it always terminates with error 'Update failed. Please restart your device and try again'.

The device updates don't get past 0%. The lights on the EXA go
"Green, unlit, yellow",
"Green, blue, yellow",
"Green, unlit, yellow",
then all unlit. Then after about 30 seconds where nothing happens, it fails.

The Android notification says "Upload failed - DFU process failed"
I have tried restarting and retrying! 😢 

For reference, here's my full info from the Android app's About window:

```
NUR firmware: 5.10-A
NUR bootloader: 1.5-A
Device firmware: 2.0.6
Device bootloader: 1
```

Perhaps I have a faulty device, do you think I should acquire another one?

**Comment by TuroRantanen** [comment]
Hi Stephen,

Seems that bootloader version is so old that you have to use a nRF Connect -tool for updating. From the link below you will find an instruction how to update your device:
https://github.com/NordicID/nur_exa_firmware/tree/master/doc

Please, update Bootloader first and then Application. You will find both files at the following link:
https://github.com/NordicID/nur_exa_firmware

Please let me know if this wasn't helpful.

Best Regards, 
Turo

**Comment by SteGriff** [comment]
Hi Turo,

Thanks for the excellent instructions, they were very helpful.

I have followed them and attempted to update the bootloader as instructed. The process appeared to complete but the device never came back on. I have captured the log; around line 195, you will see it says:

```
A 16:15:35.323 [DFU] Data object executed
A 16:15:35.324 [DFU] Upload completed in 7215 ms
D 16:15:39.522 [Callback] Connection state changed with status: 8 and new state: DISCONNECTED (0)
E 16:15:39.523 Error 8 (0x8): GATT CONN TIMEOUT
I 16:15:39.523 Disconnected
D 16:15:39.532 [Broadcast] Action received: android.bluetooth.device.action.ACL_DISCONNECTED
I 16:15:39.565 [DFU] Disconnected by the remote device
D 16:15:39.565 [DFU] gatt.refresh() (hidden)
D 16:15:39.565 [DFU] gatt.close()
```

Full log here: https://gist.github.com/SteGriff/a4d797ec40ee2fcf9b502dfa78ecf120

It seems the EXA device forcibly disconnects (like it does with the NordicID app and my app...)

**Edit:**
In my subsequent attempts to upload the bootloader (after disconnecting and restarting device) the process does not start. Log: https://gist.github.com/SteGriff/5e1ada410916897cff8e0dae5b445431

Any more advice you can offer would be much appreciated! :)

Best regards,
Ste

**Comment by mikkonid** [comment]
Hi Ste,

Since BT name changed to DfuExa, it looks like bootloader update went through correctly. 
You should be now able to upload [exa application zip](https://github.com/NordicID/nur_exa_firmware/tree/master/exa_application) same way with Nordic Semiconductor tool.

BR,
Mikko

**Comment by AriPoy** [comment]
Hi Ste, 

Is your device now totally dead or does it advertising itself as "DfuExa" ?
Have you tried to remove battery and put back on?

**Comment by SteGriff** [comment]
Thanks Mikko, I can try this on Monday. Many thanks to all of you supporting us with this!

**Comment by SteGriff** [comment]
Hi all,

Updating the bootloader and firmware of the EXA device has resolved this problem!

Thanks again for all the help
Ste

**Comment by rpspankaj** [comment]
createSocket(127.0.0.1, 4333)
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.nur.sample.NurApiSocketTransport.connect(NurApiSocketTransport.java:67)
	at com.nordicid.nurapi.NurApi.connect(NurApi.java:1834)
	at com.nur.sample.SamplesCommon.createAndConnectNurApi(SamplesCommon.java:78)
	at com.nur.sample.ExampleSetting.main(ExampleSetting.java:47)
Log[2]: 1565103931868 Transport connect failed
Log[2]: 1565103931872 NurApi.connect() : failure.
*** COULD NOT CONNECT READER ***
*** CHECK YOUR CONNECTION SETTINGS ***
*** See createTransport() in SamplesCommon.java ***
java.lang.Exception: NurApi.connect() : connection failed. connFailedAt 1
	at com.nordicid.nurapi.NurApi.connect(NurApi.java:1900)
	at com.nur.sample.SamplesCommon.createAndConnectNurApi(SamplesCommon.java:78)
	at com.nur.sample.ExampleSetting.main(ExampleSetting.java:47)
